# Generated by Django 5.1.4 on 2024-12-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('nebulosa', 'Nebulosa'), ('estrela', 'Estrela'), ('galaxia', 'Galáxia'), ('planeta', 'Planeta')], default='', max_length=20),
        ),
    ]
